name: Pull Request
on:
  push:
    branches:
    - '*'
    tags-ignore:
    - 'v*'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.3'
    - run: make
    - run: make test
    - uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: cover.html
