name: Release
on:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.3'
    - run: make
    - name: Create Archive
      run: tar czf goci-${{ github.ref }}.tar.gz build/bin/*
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      vith:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: goci-${{ github.ref }}.tar.gz
        asset_name: goci-${{ github.ref }}.tar.gz
        asset_content_type: application/gzip
